SurveyWebApplication/Models/QuestionSet.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.ComponentModel.DataAnnotations;
using SurveyWebApplication.ModelViewInfo;
namespace SurveyWebApplication.Models
{
    public class QuestionSet : BaseModel
    {
        [Key]
        public int SetId { get; set; }
        public string SetName { get; set; }
        public List<Question> QuestionList { get; set; }

    }
}

SurveyWebApplication/Controllers/QuestionSetsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using SurveyWebApplication.DAL;
using SurveyWebApplication.Models;
namespace SurveyWebApplication.Controllers
{
    public class QuestionSetsController : Controller
    {
        //
        // GET: /QuestionSets/
        [HttpGet]
        public ActionResult QuestionSet()
        {
               var databaseConnection = new DatabaseConnection();
               List<QuestionSet> data = databaseConnection.GetAllQuestionSet();
              ViewBag.JsonData = Newtonsoft.Json.JsonConvert.SerializeObject(data); 
             return View();

            
        }

        [HttpGet]
        public ActionResult QuestionSetCreate()
        {
            return View();
        }

        [HttpPost]
        public ActionResult QuestionSetCreate(String SetName, string Name)
        {
            string setName = SetName.ToString();
            string createby = "";
            string updateby = "";
            DateTime CreateDate =DateTime.Now;
            DateTime UpdateDate = Convert.ToDateTime("1900-01-01");
            string Status = "";
            string OrgId = Name.ToString();

            if (setName == "" || OrgId=="")
            {

            }
            else
            {
                var databaseConnection = new DatabaseConnection();
                var valueadd = databaseConnection.QuestionSetCreate(setName, createby, updateby, CreateDate, UpdateDate, Status, OrgId);
            }

            return RedirectToAction("QuestionSet");
        }





        [HttpGet]
        public JsonResult OrganizationList()
        {
            var databaseConnection = new DatabaseConnection();
            var list = databaseConnection.GetOrganizationList01(); 

            return Json(list, JsonRequestBehavior.AllowGet);


        }
	}
}

SurveyWebApplication/Views/QuestionSets/QuestionSet.cshtml
@model List<SurveyWebApplication.Models.QuestionSet>

@{
    ViewBag.Title = "QuestionSet";
}

<style>
    

    .cards {
        margin: 0 auto;
        display: -webkit-flex;
        display: flex;
        border-radius: 10px;
        /*-webkit-justify-content: center;
        justify-content: center;*/
        -webkit-flex-wrap: wrap;
        flex-wrap: wrap;
        margin-top: 15px;
        padding: 1%;
        -webkit-box-sizing: border-box;
        -moz-box-sizing: border-box;
        box-sizing: border-box;
        box-shadow: 0 3px 6px rgba(0,0,0,0.16), 0 3px 6px rgba(0,0,0,0.23);
    }

        .cards:hover {
            box-shadow: 0 4px 10px rgba(0,0,0,0.16), 0 4px 10px rgba(0,0,0,0.23);
        }
    .datagrid {
        width: 702px !important;
    }
  
</style>



<div class="container-fluid mb-5">
    <div class="text-center mt-5">
        <h1> Question Set</h1>
    </div>
   
    <div class="row">
        <div class="col-md-12">
            <div class=" cards " style="width: 80rem;">
                <div class="row">
                    <div class="col-md-2"></div>
                    <div class="col-md-8">
                        <div class="text-right pb-1">
                            <a href="@Url.Action("QuestionSetCreate", "QuestionSets")" class="easyui-linkbutton " data-options="iconCls:'icon-add'">Create</a>

                        </div>
                        <div class="card-body " style="width: 80rem;">
                            <table id="tbl" class="easyui-datagrid" title="Basic Question Set" data-options="method:'get'">
                                <thead>
                                    <tr>

                                        <th data-options="field:'SetName',width:'500px'"><b>Set Name</b></th>
                                        <th data-options="field:'CreateDate',width:'200px'"><b>CreateDate</b></th>

                                    </tr>
                                </thead>
                            </table>
                        </div>
                    </div>
                    <div class="col-md-2"></div>
                </div>
               
            </div>
        </div>
    </div>

</div>
<script>
    var data = @Html.Raw(ViewBag.JsonData)
 $('#tbl').datagrid({

     data:data,
 });

</script>

SurveyWebApplication/Views/QuestionSets/QuestionSetCreate.cshtml
@model SurveyWebApplication.Models.QuestionSet

@{
    ViewBag.Title = "QuestionSetCreate";
}


<style>
    .cards {
        margin: 0 auto;
        display: -webkit-flex;
        display: flex;
        border-radius: 10px;
        /*-webkit-justify-content: center;
        justify-content: center;*/
        -webkit-flex-wrap: wrap;
        flex-wrap: wrap;
        margin-top: 15px;
        padding: 1%;
        -webkit-box-sizing: border-box;
        -moz-box-sizing: border-box;
        box-sizing: border-box;
        box-shadow: 0 3px 6px rgba(0,0,0,0.16), 0 3px 6px rgba(0,0,0,0.23);
    }

        .cards:hover {
            box-shadow: 0 4px 10px rgba(0,0,0,0.16), 0 4px 10px rgba(0,0,0,0.23);
        }
</style>





<div class="container-fluid mb-5">
    <div class="text-center mt-5">
        <h1> Question Set</h1>
    </div>
    <form id="fff" method="post">
        <div class="row">
            <div class="col-md-12">
                <div class=" cards " style="width: 80rem;">                   
                    <div class="card-body">
                        <div class="row">
                            <div class="col-md-3"></div>
                            <div class="col-md-6">
                                <div class="row">
                                    <div class="col-md-4">
                                        <label for="name">Organization Name</label>
                                    </div>
                                    <div class="col-md-8">
                                        <input class="easyui-combobox " name="Name" id="OrgName" data-options="valueField:'OrgId',textField:'Name',method:'Get', url:'OrganizationList/QuestionSets'" style="width: 275px; height: 35px;">
                                    </div>
                                </div>
                                <div class="row mt-2">
                                    <div class="col-md-4">
                                        <label for="name"> Set Title</label>
                                    </div>
                                    <div class="col-md-8">
                                        <input class="easyui-textbox " name="SetName" style="width: 275px; height: 35px;">
                                    </div>
                                </div>                              
                            </div>
                            <div class="col-md-3"></div>
                        </div>
                        <div class="row">
                            <div class="col-md-6">
                                
                            </div>
                            <div class="col-md-6">
                                <br /><button type="submit" class="easyui-linkbutton " style="width:80px">Submit</button>

                            </div>
                        </div>                        
                    </div>
                </div>
            </div>
        </div>
    </form>
</div>


<script>
    debugger;
    $('#OrgName').combobox({
        prompt: 'Select Organization Name',
        valueField: 'OrgId',
        textField: 'Name',
        url: 'OrganizationList/QuestionSets',
        onLoadSuccess: function (list) {
            console.log(list);
        }
    });




    $('#fff').form('submit',
       {
           url: 'QuestionSetCreate/QuestionSets'


       });
</script>