SurveyWebApplication/Models/Questionnaires.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.ComponentModel.DataAnnotations;

namespace SurveyWebApplication.Models
{
    public class Questionnaires
    {
        [Key]
        public int QuestionId { get; set; }
        public string QuestionTitle { get; set; }
        public int OptionId { get; set; }
        
    }
}

SurveyWebApplication/Controllers/QuestionnaireController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Configuration;
using SurveyWebApplication.Models;
using SurveyWebApplication.ModelViewInfo;
using System.Data;
using System.Data.SqlClient;
using SurveyWebApplication.DAL;
namespace SurveyWebApplication.Controllers
{
    public class QuestionnaireController : Controller
    {
        //
        // GET: /Questionnaire/
        [HttpGet]
        public ActionResult QuestionTitleList()
        {
            var databaseConnection = new DatabaseConnection();
            List<Question> data = databaseConnection.GetAllQuestion();
            ViewBag.JsonData = Newtonsoft.Json.JsonConvert.SerializeObject(data); 
            return View();
        }

        [HttpGet]
        public JsonResult OptionList()
        {
            var databaseConnection = new DatabaseConnection();
            var data = databaseConnection.GetAllOptionType();

            return Json(data, JsonRequestBehavior.AllowGet);


        }



        [HttpGet]
        public ActionResult CreateOptionType()
        {
            return View();
        }
        [HttpPost]
        public ActionResult CreateOptionType(Questionnaires model)
        {
            Questionnaires q = new Questionnaires
            {
                QuestionTitle=model.QuestionTitle,
                QuestionId=model.QuestionId,
                OptionId=model.OptionId,
            };


            string Title = model.QuestionTitle;
            string id = model.OptionId.ToString();
            if (Title == null && id =="0")
            {

            }
            else
            {
                var databaseConnection = new DatabaseConnection();
                var valueadd = databaseConnection.CreateOptionType(Title, id);
                TempData["massage"] = valueadd;
                return RedirectToAction("QuestionTitleList");
            }

            return View(model);
        }
	}
}

SurveyWebApplication/Views/Questionnaire/CreateOptionType.cshtml
@{
    ViewBag.Title = "CreateOptionType";
}

<div class="container">
    <div class="jumbotron">
        
        <form id="ff" method="post" >
            <div class="row">
                <div class="col-md-2">
                    <label for="name">Question Title </label>
                </div>
                <div class="col-md-3">
                    <input class="easyui-textbox " name="QuestionTitle" style="width: 275px; height: 35px;">
                </div>
            </div>
            <div class="row">
                <div class="col-md-2">
                    <label for="email">Option Type </label>
                </div>
                <div class="col-md-3">
                    <input id="optionName" class="easyui-combobox " style="width: 275px; height: 35px;" name="OptionId" placeholder="Select Option Type" data-options="valueField:'OptionId',textField:'OptionTypeName',method:'Get', url:'OptionList/OptionType'">

                </div>
            </div>
            <div class="row">
                <div class="col-md-2">

                </div>
                <div class="col-md-3">
                    <button  type="submit" class="easyui-linkbutton "  style="width:80px">Submit</button>

                    @*<a href="javascript:void(0)" type="submit" class="easyui-linkbutton" onclick="submitForm()" style="width:80px">Submit</a>*@

                </div>
            </div>

        </form>
    </div>
</div>




<script>


    $('#optionName').combobox({
        prompt: 'Select an Option',
        valueField: 'OptionId',
        textField: 'OptionTypeName',
        url: 'OptionList/OptionType',
        onLoadSuccess: function (data) {
            console.log(data);
        }
    });

    
        $('#ff').form('submit',
        {
            url: 'CreateOptionType/Questionnaire'
           

    });
    


</script>

SurveyWebApplication/Views/Questionnaire/QuestionTitleList.cshtml
@model SurveyWebApplication.Models.Question

@{
    ViewBag.Title = "QuestionTitleList";
}

<div class="container">
    <div class="jumbotron">

        <div class="row card">
           
            <div class="col-md-12">
                <div class="row">
                    @if (TempData["massage"] != null)
                    {
                        <p class="alert alert-success">@TempData["massage"]</p>
                    }
                </div>
                <div class="text-right">
                    <a href="@Url.Action("CreateOptionType", "Questionnaire")" class="easyui-linkbutton "  data-options="iconCls:'icon-add'">Create</a>

                </div>
                <table id="tbl" class="easyui-datagrid" title="Basic Question"  data-options="method:'get'">
                    <thead>
                        <tr>
                            <th  data-options="field:'QuestionTitle',width:400"><b>OptionType Name</b></th>
                            <th data-options="field:'OptionTypeName',width:200"><b>OptionType Name</b></th>
                            
                        </tr>
                    </thead> 
                </table>

            </div>
            
        </div>
    </div>
</div>
<script>

   
        // Parse the JSON data passed from the controller
        var data = @Html.Raw(ViewBag.JsonData)

        // Create EasyUI data grid
        $('#tbl').datagrid({
            
            data: data,
            rowStyler: function(index,row){
                if (row.OptionTypeName == 'SingleSelected') {
                    return 'background: linear-gradient(90deg, hsla(216, 96%, 56%, 1) 0%, hsla(178, 64%, 65%, 1) 100%);color:#fff;font-weight:bold;';
                }
                else if (row.OptionTypeName == 'MultiSelected') {
                    return 'background: linear-gradient(90deg, hsla(260, 28%, 53%, 1) 0%, hsla(170, 42%, 71%, 1) 100%);color:#fff;font-weight:bold;';
                }
                else if (row.OptionTypeName == 'Text') {
                    return 'background: linear-gradient(90deg, hsla(97, 100%, 17%, 1) 0%, hsla(65, 14%, 83%, 1) 100%);color:#fff;font-weight:bold;';
                }
            }
        });






   
</script>