SurveyWebApplication/Controllers/OptionTypeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Configuration;
using SurveyWebApplication.Models;
using System.Data;
using System.Data.SqlClient;
using SurveyWebApplication.DAL;


namespace SurveyWebApplication.Controllers
{
    public class OptionTypeController : Controller
    {
        
        //
        // GET: /OptionType/
        [HttpGet]
        public ActionResult OptionTypeList()
        {
            var databaseConnection = new DatabaseConnection();
            List<OptionType> data = databaseConnection.GetAllOptionType();
            ViewBag.JsonData = Newtonsoft.Json.JsonConvert.SerializeObject(data);
            return View();
           
        }

        //[HttpGet]
        //public JsonResult OptionList()
        //{
        //    var databaseConnection = new DatabaseConnection();
        //    var data = databaseConnection.GetAllOptionType();

        //    return Json(data,JsonRequestBehavior.AllowGet);
           
           
        //}
        //[HttpPost]
        //public ActionResult CreateOptionType(string QuestionTitle, string OptionId)
        //{
        //    string Title = QuestionTitle.ToString();
        //    string id = OptionId.ToString(); 
        //    if (Title == "" && id == "")
        //    {

        //    }
        //    else
        //    {
        //        var databaseConnection = new DatabaseConnection();
        //        var valueadd = databaseConnection.CreateOptionType(Title, id);
        //    }
           
        //    return View();
        //}
    }
}

SurveyWebApplication/Controllers/QuestionController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Configuration;
using SurveyWebApplication.Models;
using SurveyWebApplication.ModelViewInfo;
using System.Data;
using System.Data.SqlClient;
using SurveyWebApplication.DAL;
namespace SurveyWebApplication.Controllers
{
    public class QuestionController : Controller
    {
       
        // GET: /Questionnaire/
        [HttpGet]
        public ActionResult QuestionTitleList()
        {
            var databaseConnection = new DatabaseConnection();
            List<QuestionManage> data = databaseConnection.GetAllQuestion();
            ViewBag.JsonData = Newtonsoft.Json.JsonConvert.SerializeObject(data);
            return View();
        }

        [HttpGet]
        public JsonResult OptionList()
        {
            var databaseConnection = new DatabaseConnection();
            var data = databaseConnection.GetAllOptionType();

            return Json(data, JsonRequestBehavior.AllowGet);


        }

        [HttpGet]
        public JsonResult SetList()
        {
            var databaseConnection = new DatabaseConnection();
            var data = databaseConnection.GetAllQuestionSet();

            return Json(data, JsonRequestBehavior.AllowGet);


        }



        [HttpGet]
        public ActionResult QuestionCreate()
        {
            return View();
        }
        [HttpPost]
        public ActionResult QuestionCreate(Question model)
        {
            
            string Title = model.QuestionTitle;
           
           
            string createby = "";
            string updateby = "";
            DateTime CreateDate = DateTime.Now;
            DateTime UpdateDate = Convert.ToDateTime("1900-01-01");
            string Status = "";
            if (Title == null  )
            {

            }
            else
            {
                var databaseConnection = new DatabaseConnection();
                var valueadd = databaseConnection.CreateQuestion(Title, createby, updateby, CreateDate, UpdateDate, Status);
                TempData["massage"] = valueadd;
                return RedirectToAction("QuestionTitleList");
            }

            return View(model);
        }
	}
}

SurveyWebApplication/Controllers/SetManageController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using SurveyWebApplication.Models;
using SurveyWebApplication.ModelViewInfo;
using SurveyWebApplication.DAL;
using Newtonsoft.Json;
namespace SurveyWebApplication.Controllers
{
    public class SetManageController : Controller
    {
        //
        // GET: /QuestionSet/
        [HttpGet]
        public ActionResult SetManageList()
        {

            var databaseConnection = new DatabaseConnection();
            //List<Question> data = databaseConnection.GetAllQuestionList();
            List<QuestionViewModel> view = databaseConnection.GetAllQuestionView();
            ViewBag.JsonData = view;



            List<SetManage> oldSet = databaseConnection.GetAllSetManage();
            List<SetManageInfo> newSet = new List<SetManageInfo>();
            var data = oldSet.Select(x => x.SetId).Distinct();
            foreach (var item in data)
            {
                var sdata = oldSet.Where(e => e.SetId == item).ToList();
                SetManageInfo info = new SetManageInfo
                {
                    SetManageId=sdata[0].SetManageId,
                    SetId = sdata[0].SetId,
                    SetName = sdata[0].SetName,
                    SetManageList = new List<SetManage>()

                };

                foreach (var iitem in sdata)
                {
                    SetManage SetManageItem = new SetManage
                    {
                        SetId = iitem.SetId,
                        SetName = iitem.SetName,
                        QuestionId = iitem.QuestionId,
                        QuestionTitle = iitem.QuestionTitle,
                    };
                    info.SetManageList.Add(SetManageItem);
                }
                newSet.Add(info);
            }


            
            return View(newSet);
        }

        [HttpGet]
        public JsonResult SetList()
        {
            var databaseConnection = new DatabaseConnection();
            var data = databaseConnection.GetAllQuestionSet();

            return Json(data, JsonRequestBehavior.AllowGet);


        }


        [HttpPost]
        public ActionResult SetAdd(QuestionViewInfo model)
        {
            var databaseConnection = new DatabaseConnection();
            string SetId = (model.SetId).ToString();
            model.list = JsonConvert.DeserializeObject<List<QuestionIdList>>(model.Connectinglist);
            foreach (var item in model.list)
            {
                string QuestionId = (item.QuestionId).ToString();
                if (QuestionId == "0" || SetId == "0")
                {
                    TempData["notify"] = "Please Select Set Name";
                    return View();
                }
                else
                {
                    var result = databaseConnection.SetManageAdd(SetId, QuestionId);

                }
            }

            var Success = true;

            return View("SetManageList/SetManage", Success);
        }



        [HttpPost]
        public ActionResult SetChange(SetChangeInfo data)
        {
            var databaseConnection = new DatabaseConnection();
           
                data.datalist = JsonConvert.DeserializeObject<List<RemoveList>>(data.Connectingstringlist);
                foreach (var item in data.datalist)
                {
                    string QuestionId = (item.QuestionId).ToString();
                    string SetId = (item.SetId).ToString();

                    var result = databaseConnection.SetRemove(SetId, QuestionId);
                }

            var Success=true;

            return View("SetManageList/SetManage", Success);

        }





    }
}

SurveyWebApplication/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    <link href="~/Content/toastr.min.css" rel="stylesheet" />
    <script src="~/Content/toastr.min.js"></script>
    <link href="~/Content/CustomStyle.css" rel="stylesheet" />   
    <link href="~/Content/EasyUi/easyui.css" rel="stylesheet" />
    <link href="~/Content/EasyUi/icon.css" rel="stylesheet" />
    <link href="~/Content/color.css" rel="stylesheet" />
   
    <link href="~/Content/bootstrap.min.css" rel="stylesheet" />
    <script src="~/Content/bootstrap.bundle.min.js"></script>
    <script src="~/Content/EasyUi/jquery.min.js"></script>
    <script src="~/Content/EasyUi/jquery.easyui.min.js"></script>
 
   
    <style>
        .background {
            background: -webkit-gradient(linear,left top,left bottom,color-stop(1,#1f4b65),color-stop(0,#83b7b7));
            border-color: black;
            border-radius: 2px;
            color: white !important;
        }

        .navbar-nav .nav-link.active, .navbar-nav .nav-link.show {
            color: white !important;
        }
        #headcolor {
            color: white !important;
        }
      
    </style>

</head>
<body>   

    <nav class="navbar background navbar-expand-md navbar-light bg-light mb-4">
        <div class="container">
            <a class="navbar-brand" id="headcolor" href="#">SurveyApplication</a>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarCollapse">
                <ul class="navbar-nav me-auto mb-2 mb-md-0">
                    <li class="nav-item">
                        <a class="nav-link active" href="@Url.Action("OrganizationList", "Organization")">Organization</a>
                    </li>
                    
                    <li class="nav-item">
                        <a class="nav-link active" href="@Url.Action("QuestionSet", "QuestionSets")">SurveySet</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link active" href="@Url.Action("OptionTypeList", "OptionType")">OptionType</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link active" href="@Url.Action("QuestionTitleList", "Question")">SurveyTitle</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link active" href="@Url.Action("SetManageList", "SetManage")">SetManage</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link active" href="@Url.Action("QuestionCreate", "QuestionManage")">SurveyCreate</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link active" href="@Url.Action("SetList", "SurveyManage")">Survey</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link active" href="@Url.Action("OrganizationSurvey", "SurveyManage")">SurveyResult</a>
                    </li>
                </ul>
                <form class="d-flex" id="headcolor">
                    <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search">
                    <button class="btn btn-success" type="submit">Search</button>
                </form>
            </div>
        </div>
    </nav>




    <div class="container body-content">
        @RenderBody()
     
    </div>
      
    <footer class="footer mt-auto py-3 bg-light fixed-bottom">
        <div class="container">
            <p>&copy; @DateTime.Now.Year - Developed By  <a href="https://mediasoftbd.com/" style="text-decoration:none !important">MediaSoft Data System Limited.</a></p>
        </div>
    </footer>
    
   
</body>
</html>