SurveyWebApplication/Controllers/SurveyManageController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using SurveyWebApplication.DAL;
using SurveyWebApplication.Models;
using SurveyWebApplication.ModelViewInfo;
using Newtonsoft.Json;
namespace SurveyWebApplication.Controllers
{
    public class SurveyManageController : Controller
    {
        //
        // GET: /SurveyManage/
        [HttpGet]
        public ActionResult SurveyQuestion()
        {
            var databaseConnection = new DatabaseConnection();
            string setId =Request.QueryString["SetId"]==null?"": Request.QueryString["SetId"].ToString();
            List<SurveyViewInfo> questionlist = databaseConnection.GetAllSurveyList(setId);

            List<Question> newQuestionList = new List<Question>();
            var data = questionlist.Select(x => x.QuestionId).Distinct();
            foreach (var item in data)
            {
                var sdata = questionlist.Where(e => e.QuestionId == item).ToList();
                Question info = new Question
                {
                    QuestionId = sdata[0].QuestionId,
                    OptionTypeId=sdata[0].OptionTypeId,
                    QuestionTitle = sdata[0].QuestionTitle,
                    OptionList = new List<Options>()

                };

                foreach (var iitem in sdata)
                {
                    Options SetManageItem = new Options
                    {
                        OptionId = iitem.OptionId,
                        OptionName = iitem.OptionName,
                        OptionTypeId = iitem.OptionTypeId,
                        IsCorrect = iitem.IsCorrect,
                    };
                    info.OptionList.Add(SetManageItem);
                }
                newQuestionList.Add(info);
            }

            return View(newQuestionList);
        }


        [HttpGet]
        public ActionResult SetList()
        {
            var databaseConnection = new DatabaseConnection();           
            List<QuestionSet> questionlist = databaseConnection.GetAllQuestionSet();
            return View(questionlist);
        }



        [HttpPost]
        public ActionResult AnswerSubmit(SurveyModel model)
        {
            var databaseConnection = new DatabaseConnection();

            string CustomerId = model.CustomerId.ToString();
            string createby = "";           
            DateTime CreateDate = DateTime.Now;
           
            model.QuestionTitleList = JsonConvert.DeserializeObject<List<Question>>(model.QuestionTitleString);
            foreach (var item in model.QuestionTitleList)
            {
                string QuestionId = item.QuestionId.ToString();               
                var option = item.OptionList;

                foreach (var iitem in option)
                {
                    string OptionId = iitem.OptionId.ToString();
                    string OptionName = iitem.OptionName.ToString();
                    string QuestionTypeId = iitem.OptionTypeId.ToString();
                    var result = databaseConnection.AnswerSubmit(CustomerId, QuestionId, OptionId, OptionName, QuestionTypeId, createby, CreateDate);
                }
            }
            return View();
        }


        [HttpGet]
        public ActionResult Test(string dvalue)
        {
            var databaseConnection = new DatabaseConnection();
            string setId = dvalue == null ? "" : dvalue;
            List<SurveyViewInfo> questionlist = new List<SurveyViewInfo>();
            if (setId == "")
            {
                questionlist = databaseConnection.GetAllSurveyList01();
            }
            else
            {
                questionlist = databaseConnection.GetAllSurveyList(setId);
            }
            

            List<Question> newQuestionList = new List<Question>();
            var idata = questionlist.Select(x => x.QuestionId).Distinct();
            foreach (var item in idata)
            {
                var sdata = questionlist.Where(e => e.QuestionId == item).ToList();
                Question info = new Question
                {
                    QuestionId = sdata[0].QuestionId,
                    OptionTypeId = sdata[0].OptionTypeId,
                    QuestionTitle = sdata[0].QuestionTitle,
                    OptionList = new List<Options>()

                };

                foreach (var iitem in sdata)
                {
                    Options SetManageItem = new Options
                    {
                        OptionId = iitem.OptionId,
                        OptionName = iitem.OptionName,
                        OptionTypeId = iitem.OptionTypeId,
                        IsCorrect = iitem.IsCorrect,
                        AnsCount=iitem.AnsCount
                    };
                    info.OptionList.Add(SetManageItem);
                }
                newQuestionList.Add(info);
            }
            return View(newQuestionList);
        }


        [HttpGet]
        //[Route("SurveyManage/ModalData/{id}")]
        public JsonResult ModalData(int id)
        {
            var databaseConnection = new DatabaseConnection();
            List<CustomerInformation> result = databaseConnection.GetCustomer(id);
            
            return Json(result, JsonRequestBehavior.AllowGet);
        }



        [HttpGet]
        public JsonResult SetNameList()
        {
            var databaseConnection = new DatabaseConnection();
            var data = databaseConnection.GetAllQuestionSet();

            return Json(data, JsonRequestBehavior.AllowGet);


        }


        [HttpGet]
        public JsonResult CustListList()
        {
            var databaseConnection = new DatabaseConnection();
            var data = databaseConnection.GetAllCustomer();

            return Json(data, JsonRequestBehavior.AllowGet);


        }





        [HttpGet]

        public ActionResult OrganizationSurvey(string fromDate, string toDate)
        {
            var dataConnection = new DatabaseConnection();
            string frmdate = fromDate == null ? "" : fromDate.ToString();
            string todate = fromDate == null ? "" : toDate.ToString();
            List<Organization> list = dataConnection.GetOrganizationList(frmdate, todate);
            //ViewBag.list = list;
            ViewBag.Datad = list;

            return View();
        }


        


	}
}

SurveyWebApplication/Views/SurveyManage/OrganizationSurvey.cshtml
@model List<SurveyWebApplication.Models.Organization>

@{
    ViewBag.Title = "OrganizationSurvey";
    int k = 1;
}


<style>
    a {
        text-decoration: none;
        font-family: Constantia;
    }

    .padtop {
        padding-top: 1.8rem !important;
    }
</style>
<div class=" shadow-lg p-3 rounded bg-light">
    <h2 class="text-center">Survey List</h2><hr />
    <div class="row">
        <form id="www" method="post">

            <div class="row">
                <div class="col-md-1">
                    <label class="textbox-label">From Date</label>
                </div>
                <div class="col-md-3">
                    <input class="easyui-datetimebox" id="fromDate"
                           data-options="required:true,showSeconds:false" value="3/4/2010 " style="width: 250px; height: 35px;">
                </div>
                <div class="col-md-1">
                    <label class="textbox-label">To Date</label>
                </div>
                <div class="col-md-3">
                    <input class="easyui-datetimebox" id="toDate"
                           data-options="required:true,showSeconds:false" value="3/4/2010 " style="width: 250px; height: 35px;">
                </div>
                <div class="col-md-1">
                    <button type="submit" class="easyui-linkbutton c1" id="btnfilter" style="width:80px">Filter</button>
                </div>
            </div>

        </form>
    </div>


   
        @if (ViewBag.Datad.Count>0)
            {
            <div class="row mt-5" style="font-size:28px; ">
                @foreach (var item in ViewBag.Datad)
                {
                    <div class="col-md-1"></div>
                    <div class="col-md-11 mt-1">
                        <a href="@Url.Action("Test", "SurveyManage", new { OrgId = @item.OrgId })" id="datafilter" class="pl-2">@k. @item.Name </a>
                    </div>
                    k++;
                }
            </div>
            }
        else
        {
             <div class="row mt-5" style="font-size:28px; ">
              
                   
                    <div class="col-md-12 mt-1 text-center">
                        <p class="bg-light">No data available.</p>
                    </div>
                 
            </div>
           
        }

</div>




<script>
    debugger;
    const date = new Date();
    let currentDay = String(date.getDate()).padStart(2, '0');
    let currentMonth = String(date.getMonth() + 1).padStart(2, "0");
    let currentYear = date.getFullYear();

    $('#fromDate').datetimebox({
        value: '${currentDay}-${currentMonth}-${currentYear}',
        format: 'dd-MMM-yyyy',
        required: true,
        showSeconds: false
    });


    $('#toDate').datetimebox({
        value: '${today.getDate()}/{today.getMonth()}/${today.getFullYear()}',
        format: 'dd-MMM-yyyy',
        required: true,
        showSeconds: false
    });


   

    $('#btnfilter').click(function (e) {
        e.preventDefault();
        debugger;
        var fromDate = $('#fromDate').val();
        var toDate = $('#toDate').val();
        
        window.location.href = '@Url.Action("OrganizationSurvey", "SurveyManage")?fromDate=' + fromDate + '&toDate=' + toDate;

        //if (name == null) {

        //}
        //$.ajax({
        //    type: "post",
        //    url: "FilterSurvey/SurveyManage",
        //    data: { fromDate: fromDate, toDate: toDate },
        //    dataType: 'json',
        //    success: function (response) {
              

                

        //    },
        //    error: function () {
        //        //error code here
               
        //    }
        //});

    });



</script>

SurveyWebApplication/Views/SurveyManage/SetList.cshtml
@model List<SurveyWebApplication.Models.QuestionSet>
@{
    ViewBag.Title = "SetList";
}
<style>
    .padtop {
        padding-top: 1.8rem !important;
    }

    .backcolor {
        background: #dee2e6;
    }

        .backcolor:hover {
            box-shadow: 0 4px 10px rgba(0,0,0,0.16), 0 4px 10px rgba(0,0,0,0.23);
        }
</style>

<div class="container-fluid mt-2">
    <div class="jumbotron">
        <div class="row mt-2">
            <h2 class="text-center">Set Wise Survey</h2>
        </div>
        <div class="row">
            @foreach (var item in Model)
            {
                <div class="col-md-2 mt-1">
                    <div class="card shadow-lg p-1 mb-3  backcolor  text-center" style="height:100px;">
                        <h2 class="padtop">
                        <input id="hiddenSetId" name="@item.SetId" value="@item.SetId" type="hidden" class="SetId">
                            <a href="@Url.Action("SurveyQuestion", "SurveyManage", new { SetId = @item.SetId })" class="btn btn-primary btn-sm">@item.SetName</a>
                        </h2>
                    </div>
                </div>
            }

        </div>
    </div>
</div>

SurveyWebApplication/Views/SurveyManage/SurveyQuestion.cshtml
@model List<SurveyWebApplication.Models.Question>
@{
    ViewBag.Title = "SurveyQuestion";
    int k = 1;
}

<style>
    .custom-accordion-button {
        //-bs-accordion-btn-padding-x: 0.75rem !important;
        vertical-align: middle !important;
    }

    a {
        text-decoration: none;
    }
    .custom-accordion-button {
        background-color: #e7e9e7 !important;
    }
    .radiobutton  {
        width: 25px !important;
        height: 25px !important;
    }
    .checkbox {
        width: 25px !important;
        height: 25px !important;
    }
</style>
<div class="container-fluid mb-5 bg-light ">
    <div class="jumbotron ">
        <form id="Survey" method="post">
            <div class="row">
                <div class="col-md-6 pb-3">
                    <div class="row">
                        <div class="col-md-3">
                            <label for="email">Customer</label>
                        </div>
                        <div class="col-md-5">
                            <input id="Customer" class="easyui-combobox " style="width: 275px; height: 35px;" name="Name" data-options="valueField:'CustomerId',textField:'CustomerName',method:'Get', url:'CustListList/SurveyManage'">

                        </div>
                    </div>
                </div>
                <div class="col-md-6">
                    <div class="">
                        <h3>Survey</h3>
                    </div>
                </div>

            </div>


            @for (int i = 0; i < Model.Count; i++)
            {

                <div class="accordion custom-accordion-button bg-light" id="accordionExample-@i" style=" ">
                    <div class="accordion-item ">
                        <h2 class="accordion-header">
                            <a class="accordion-button .custom-accordion-button" data-bs-toggle="collapse" data-bs-target="#collapseOne-@i" aria-expanded="true" aria-controls="collapseOne-@i">
                                <label class="textbox-label textbox-label-top titleName " id="@Model[i].QuestionId" style="padding:1px; font-size:20px;">@k.  @Model[i].QuestionTitle</label>
                                <input id="hiddenQtyId" name="@Model[i].OptionTypeId" value="@Model[i].OptionTypeId" type="hidden" class="OptionTypeId">
                                <input id="hiddenQId" value="@Model[i].QuestionId" name="@Model[i].QuestionId " type="hidden" class="QuestionId">

                            </a>

                        </h2>
                        <div id="collapseOne-@i" class="collapse" data-bs-parent="#accordionExample-@i">
                            <div class="accordion-body">
                                @for (int j = 0; j < Model[i].OptionList.Count; j++)
                                {
                                    if (@Model[i].OptionList[j].OptionTypeId == 1)
                                    {
                                        <div class="row">

                                            <div class="col-md-1">

                                            </div>
                                            <div class="col-md-8">

                                                <input type="radio" name="questionResponses[@i].check" id="CheckOptionId" value="@Model[i].OptionList[j].OptionId" class="easyui-radiobutton optId">
                                                <label class="textbox-label " style="width:80%; font-size:20px;">@Model[i].OptionList[j].OptionName</label>
                                            </div>
                                            <div class="col-md-3"></div>
                                        </div>
                                    }
                                    else if (@Model[i].OptionList[j].OptionTypeId == 2)
                                    {
                                        <div class="row">

                                            <div class="col-md-1">

                                            </div>
                                            <div class="col-md-8">

                                                <input type="checkbox" name="questionResponses[@i].check" id="CheckOptionId" value="@Model[i].OptionList[j].OptionId" class="easyui-checkbox optId">
                                                <label class="textbox-label " style="width: 80%; font-size: 20px;">@Model[i].OptionList[j].OptionName</label>
                                            </div>
                                            <div class="col-md-3"></div>
                                        </div>
                                    }
                                    else if (@Model[i].OptionList[j].OptionTypeId == 3)
                                    {
                                        <div class="row ">
                                            <div class="col-md-1"></div>
                                            <div class="col-md-8">
                                                <input class=" form-control  textField" id="textNode[@i]" name="questionResponses[@i].TextField" style="width: 100%; height: 60px; ">
                                            </div>
                                        </div>
                                    }

                                }
                            </div>
                        </div>
                    </div>
                </div>

                                k++;
            }
            <div class="row mt-2 text-center">
                <div class="col-md-4"></div>
                <div class="col-md-4">
                    <button class="easyui-linkbutton c1" type="submit" style="width:100%; " id="btnSurvey"><h2>Survey Save</h2></button>

                </div>
                <div class="col-md-4"></div>
            </div>

        </form>

    </div>
</div>





<script>

   
    $('#Customer').combobox({
        prompt: 'Select an CustomerName',
        valueField: 'CustomerId',
        textField: 'CustomerName',
        url: 'CustListList/SurveyManage',
        onLoadSuccess: function (data) {
            console.log(data);
        }
    });






    $('#btnSurvey').click(function (e) {

        e.preventDefault();

        var Qtype = document.getElementsByClassName('OptionTypeId');
        var optId = document.getElementsByClassName('optId');
        var title = document.getElementsByClassName('QuestionId');
        var Text = document.getElementsByClassName('textField');
        var checkboxId = document.getElementById('CheckOptionId');


        var model = {
            CustomerId: $('#CustomerId').val(),
            QuestionTitleList: []

        };
        model.QuestionTitleList = [];

        for (let i = 0; i < title.length; i++) {
            var qid = title[i].value;
            var typeid = Qtype[i].value
            var optionList = [];

            var Opts = document.getElementsByName("questionResponses[" + i + "].check");



            if (typeid != 3) {
                for (var n = 0; n < Opts.length; n++) {
                    var ischecked = Opts[n].checked;
                    if (ischecked) {
                        optionList.push({
                            OptionId: Opts[n].value,
                            OptionTypeId: Qtype[i].value,
                            OptionName: ''
                        });
                    }
                }


            } else {

                var textElements = document.getElementsByName("questionResponses[" + i + "].TextField");

                var textValue = textElements[0].value;
                optionList.push({
                    OptionId: 0,
                    OptionTypeId: Qtype[i].value,
                    OptionName: textValue

                });



            }

            model.QuestionTitleList.push({
                QuestionId: qid,
                OptionList: optionList
            });

        }
        model.QuestionTitleList.OptionListstring = JSON.stringify(model.QuestionTitleList.OptionList);
        model.QuestionTitleString = JSON.stringify(model.QuestionTitleList);
        debugger
        console.log(model);

        $.ajax({
            type: "POST",
            url: "AnswerSubmit/SurveyManage",
            data: model,
            dataType: 'json',

            success: function (response) {
                debugger;
                if (response == "Success") {
                    window.location.reload();

                }


            },
            error: function () {
                //error code here
                debugger;
                window.location.reload();
            }
        });

    });

</script>

SurveyWebApplication/Views/SurveyManage/Test.cshtml
@model List<SurveyWebApplication.Models.Question>
@{
    ViewBag.Title = "SurveyQuestion";
    int k = 1;
}

<style>
    .custom-accordion-button {
        //-bs-accordion-btn-padding-x: 0.75rem !important;
        vertical-align: middle !important;
    }

    a {
        text-decoration: none;
    }

    .custom-accordion-button {
        background-color: #e7e9e7 !important;
    }

    .radiobutton {
        width: 25px !important;
        height: 25px !important;
    }

    .checkbox {
        width: 25px !important;
        height: 25px !important;
    }

    .custbtn {
        padding: 0px 0px 0px 0px !important;
    }

    table {
        border-collapse: collapse;
        width: 100%;
        margin-top: 20px;
    }

    th, td {
        border: 1px solid #dddddd;
        padding: 8px;
        text-align: left;
    }

    th {
        background-color: #f2f2f2;
    }

    tr:nth-child(even) {
        background-color: #f9f9f9;
    }
</style>
<div class="container-fluid mb-5 bg-light ">
    <div class="jumbotron ">
        <form id="Survey" method="post">
            <div class="row">
                <div class="col-md-6 pb-3">
                    <div class="row">
                        <div class="col-md-2">
                            <label for="email">Set Name</label>
                        </div>
                        <div class="col-md-5">
                            <input id="setName" class="easyui-combobox " style="width: 275px; height: 35px;"  data-options="valueField:'SetId',textField:'SetName',method:'Get', url:'SetNameList/SurveyManage'">

                        </div>
                        <div class="col-md-1"></div>
                        <div class="col-md-2 mt-1">
                            <button class="easyui-linkbutton c1" type="submit" id="SetSearch">Search</button>
                        </div>
                    </div>
                </div>
                <div class="col-md-6">
                    <div class="">
                        <h3>Survey Report Show</h3>
                    </div>
                </div>

            </div>


            @for (int i = 0; i < Model.Count; i++)
            {

                <div class="accordion custom-accordion-button bg-light" id="accordionExample-@i" style=" ">
                    <div class="accordion-item ">
                        <h2 class="accordion-header">
                            <a class="accordion-button .custom-accordion-button" data-bs-toggle="collapse" data-bs-target="#collapseOne-@i" aria-expanded="true" aria-controls="collapseOne-@i">
                                <label class="textbox-label textbox-label-top titleName " id="@Model[i].QuestionId" style="padding:1px; font-size:20px;">@k.  @Model[i].QuestionTitle</label>
                                <input id="hiddenQtyId" name="@Model[i].OptionTypeId" value="@Model[i].OptionTypeId" type="hidden" class="OptionTypeId">
                                <input id="hiddenQId" value="@Model[i].QuestionId" name="@Model[i].QuestionId " type="hidden" class="QuestionId">

                            </a>

                        </h2>
                        <div id="collapseOne-@i" class="collapse" data-bs-parent="#accordionExample-@i">
                            <div class="accordion-body">
                                @for (int j = 0; j < Model[i].OptionList.Count; j++)
                                {
                                    if (@Model[i].OptionList[j].OptionTypeId == 1)
                                    {
                                        <div class="row">

                                            <div class="col-md-1">

                                            </div>
                                            <div class="col-md-8">

                                                <input type="radio" name="questionResponses[@i].check" id="CheckOptionId" value="@Model[i].OptionList[j].OptionId" class="easyui-radiobutton optId" disabled>
                                                <label class="textbox-label " style="width:80%; font-size:20px;">@Model[i].OptionList[j].OptionName</label>
                                                <button id="btnResponseid[@i]" class="btn btn-primary custbtn" type="button" onclick="loadOptionDetails(@Model[i].OptionList[j].OptionId)">
                                                    <input type="hidden" name="questionResponses[@i]" id="CountId" value="@Model[i].OptionList[j].OptionId">
                                                    <span class="rounded-pill badge  ">@Model[i].OptionList[j].AnsCount</span>
                                                </button>
                                            </div>
                                            <div class="col-md-3"></div>
                                        </div>
                                    }
                                    else if (@Model[i].OptionList[j].OptionTypeId == 2)
                                    {
                                        <div class="row">

                                            <div class="col-md-1">

                                            </div>
                                            <div class="col-md-8">

                                                <input type="checkbox" name="questionResponses[@i].check" id="CheckOptionId" value="@Model[i].OptionList[j].OptionId" class="easyui-checkbox optId" disabled="disabled">
                                                <label class="textbox-label " style="width: 80%; font-size: 20px;">@Model[i].OptionList[j].OptionName</label>
                                                <button id="btnResponseid" class="btn btn-info custbtn" type="button" onclick="loadOptionDetails(@Model[i].OptionList[j].OptionId)">
                                                    <input type="hidden" name="questionResponses[@i]" id="CountId[@i]" value="@Model[i].OptionList[j].OptionId">
                                                    <span class="rounded-pill badge ">@Model[i].OptionList[j].AnsCount</span>
                                                </button>
                                            </div>
                                            <div class="col-md-3"></div>
                                        </div>
                                    }
                                    else if (@Model[i].OptionList[j].OptionTypeId == 3)
                                    {
                                        <div class="row ">
                                            <div class="col-md-1"></div>
                                            <div class="col-md-8">
                                                <input class=" form-control  textField" id="textNode[@i]" name="questionResponses[@i].TextField" style="width: 100%; height: 60px; ">
                                            </div>
                                        </div>
                                    }

                                }
                            </div>
                        </div>
                    </div>
                </div>

                                k++;
            }
            @*<div class="row mt-2 text-center">
                <div class="col-md-4"></div>
                <div class="col-md-4">
                    <button class="easyui-linkbutton c1" type="submit" style="width:100%; " id="btnSurvey"><h2>Survey Save</h2></button>

                </div>
                <div class="col-md-4"></div>
            </div>*@

        </form>
        <div class="row">
            <div class="line text-center">
                <div class="lineL"></div>
                <div class="" style="display:inline-block;">Survey Report </div>
                <div class="lineR"></div>
            </div>
        </div>

    </div>


    <!-- Modal -->
    <div class="modal fade" id="myModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
        <div class="modal-dialog">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title" id="exampleModalLabel">Customer List</h5>
                    <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                </div>
                <div class="modal-body">

                    <div id="tableContainer"></div>

                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
                    @*<button type="button" class="btn btn-primary">Save changes</button>*@
                </div>
            </div>
        </div>
    </div>







</div>







<script>

    $('#setName').combobox({
        prompt: 'Select an Set',
        valueField: 'SetId',
        textField: 'SetName',
        url: 'SetNameList/SurveyManage',
        onLoadSuccess: function (data) {
            console.log(data);
        }
    });

    function createTable(containerId, dataArray)
    {
        debugger
        var container = document.getElementById(containerId);
        var table = document.createElement('table');
        var thead = document.createElement('thead');
        var tbody = document.createElement('tbody');

        // Create header row
        var headerRow = document.createElement('tr');
        for (var key in dataArray[0]) {
            var th = document.createElement('th');
            th.textContent = key;
            headerRow.appendChild(th);
        }
        thead.appendChild(headerRow);
        table.appendChild(thead);

        // Create data rows
        dataArray.forEach(function (item) {
            var row = document.createElement('tr');
            for (var key in item) {
                var td = document.createElement('td');
                td.textContent = item[key];
                row.appendChild(td);
            }
            tbody.appendChild(row);
        });

        table.appendChild(tbody);
        container.appendChild(table);


    }


    function loadOptionDetails(optId) {
        debugger;
        $.ajax({
            url: "ModalData/" + optId,
            type: 'GET',
            success: function (result) {
                var modalDataElement = $('#tableContainer');
                modalDataElement.empty();
                debugger;
                if (result.length > 0)
                {
                    debugger;
                    createTable('tableContainer', result);
                   
                } else {
                    modalDataElement.append('<div class="text-center"> Data Not Found </div> ');
                }



                $('#myModal').modal('show');
            },
            error: function () {
                debugger;
            }
        });



    }

    $('#SetSearch').click(function (e) {
        e.preventDefault();
        debugger
        var dvalue =$('#setName').val();
        window.location.href = '@Url.Action("Test", "SurveyManage")?dvalue=' + dvalue;

    });
   

</script>